server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/freedom9/spring-cloud-hoxton-config.git
          # 搜索目录
          search-paths:
            - spring-cloud-hoxton-config
    # 读取分支
    label: master

  # rabbitmq相关配置 15672是web管理界面的端口，5672是MQ访问的端口
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/

# rabbitmq相关配置，暴露刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
