server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com
  client:
    # false表示不向注册中心注册自己，默认为true
    register-with-eureka: false
    # false表示自己端就是注册中心，职责就是维护服务实例，并不需要去检索服务，默认为true
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/